spring:
  datasource:
    name: test
    url: jdbc:mysql://${marketcenter.database.address}:3306/${marketcenter.database.name}?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=UTC
    username: ${marketcenter.database.username}
    password: ${marketcenter.database.password}
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name:  com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 50
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  profiles:
    active: dev
server:
  port: ${marketcenter.server.port}
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000


mybatis:
  mapperLocations: classpath:sqlmap/*.xml
  typeAliasesPackage: com.zhao.marketcenter.dao.entity

#dubbo:
#  application:
#    name: boot-duboo-provider
#  # 指定注册协议和注册地址  dubbo推荐使用zookeeper作为注册中心，并且在start依赖中引入了zookeeper的java客户端Curator
#  registry:
#    protocol: zookeeper
#    address: 127.0.0.1:2181
#  protocol.name: dubbo